name: CC-Visualizer

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stats-generation:
    runs-on: ubuntu-latest

    steps:
      # Check out repository
      - uses: actions/checkout@v3

      - name: Print Run ID
        run: echo "Run ID:$GITHUB_RUN_ID"

      - name: Print Git SHA
        run: echo "Git SHA:$GITHUB_SHA"

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache dependencies
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the Java project with Maven
      - name: Build with Maven
        run: mvn -B clean install --file ./pom.xml

      # Generate all statistics images
      - name: Generate images
        run: mvn spring-boot:run

      # Commit all changed files to the repository
      - name: Commit to the repo
        run: |
          git config --global user.name "shriyansh"
          git config --global user.email "rishabhs2612@gmail.com"
          git add .
          git commit -m 'Update generated files' || true
          git push
